### ISSUE TITLE
Improve Custom Model UI

### ISSUE THREAD

**Issue by wbond** [github-early-access/copilot-custom-models-beta#12]
**Describe the bug**

This is subjective UX feedback.

Right now there appears to be a concept of a "model" that has a name. Additionally, there are training runs of that model.

Currently the model name is repeated for each training run. Additionally, you can not click on the model name to see the training run details.

**To Reproduce**
1. Go to Copilot > Custom model
2. Have at least one training
3. Try clicking on the training to see details - not possible
4. Look at the list of trainings and see how the model name is repeated for each training, resulting in N+1 copies of the model name on the page

**Expected behavior**

A standard approach to UX is to click on the name of something to see details.

Also, currently there is no way in the UI to distinguish between the trainings except by the created subheading.

It would probably make sense to have some sort of user friendly name that is based on the date created, or an auto-incrementing counter. E.g. "Training 1", "Training 2".

**Screenshots**

The items in red are all duplicate - N+1 instances where N is the number of trainings. The items in blue should be clickable, and ideally unique names in some way.

![CleanShot 2024-10-18 at 16 31 48@2x](https://github.com/user-attachments/assets/b7c98d18-caf9-4773-b892-423e71515551)

**Additional context**

**Comment by justincampbell** [comment]
Thanks for the feedback! We're looking into both suggestions.

**Comment by justincampbell** [comment]
The pipeline name is now clickable.

We're still thinking about how to represent the model "name" for future releases where there may be multiple models per org/etc. Thanks for the input on this!
