### ISSUE TITLE
[Training Error]: Juniper

### ISSUE THREAD

**Issue by thomasphorton** [github-early-access/copilot-custom-models-beta#13]
### Pipeline ID

94b77b8f-7182-493c-90bd-bdcb7f7b117b

**Comment by Chaseshak** [comment]
Hi @thomasphorton! We noticed this error and have filed an issue with our model team. You can track that here (private issue): https://github.com/github/copilot-custom-model/issues/418

**Comment by thomasphorton** [comment]
I see that the related bug was fixed, should I tell the customer to re-train now?

**Comment by Chaseshak** [comment]
@thomasphorton Yes, they can retrain now, the fix was just deployed!

**Comment by thomasphorton** [comment]
Hi! Just heard that they ran into another error:

>Thanks for providing the fix. Unfortunately, the custom model training failed again.
>2024-10-22 11:18:20Pipeline ID: d0d9959f-f517-44e4-b604-76646d0f577a, Stage ID: 651fadbe-6656-4cf5-9e9c-546b449b2b63

**Comment by Chaseshak** [comment]
Hey @thomasphorton - Sorry for the churn here, we ran into a quota issue in Azure around training. We've since resolved this and they should be able to submit again.

We're working to make things more robust during the beta, appreciate you and the customer submitting again!

**Comment by thomasphorton** [comment]
Hi! Another training error after 5 days:

```
2024-10-25 08:43:25Pipeline ID: ed23ccc3-67d3-4035-b086-b1856f255678, Stage ID: 90cd8bfa-f28d-4328-a6e0-c77db274e3d7
```

**Comment by Chaseshak** [comment]
Hi @thomasphorton they should be good to train again! We've fixed an underlying issue with Microsoft partners as well as a bug in our quality evaluation process. Thanks to you and Juniper for your patience!

**Comment by thomasphorton** [comment]
The model trained successfully, thank you!
