### ISSUE TITLE
[Training Error]: FineTunedModelDogfoodersEMU

### ISSUE THREAD

**Issue by monil-patel** [github-early-access/copilot-custom-models-beta#14]
### Pipeline ID

48c77481-4689-4f37-8678-12ff80fe567d

we hit back to back failures this time around, figured someone may want to take a look

**Comment by Chaseshak** [comment]
Hi @monil-patel! Thanks for the report. We've already identified the cause and are rolling out a fix shortly. I'll let you know when we've released the fix and you can retrain. Thanks!

**Comment by Chaseshak** [comment]
@monil-patel We've shipped a fix for this, can you please try submitting another retrain?

**Comment by justincampbell** [comment]
This looks to be fixed, let us know if you have any further issues or questions!
