### ISSUE TITLE
[Training Error]: The pipeline is stuck at "Fine-tuning Model" phase for more than 7 hours while I am opening this issue

### ISSUE THREAD

**Issue by junli-lyft** [github-early-access/copilot-custom-models-beta#8]
### Pipeline ID

57192bb9-45fd-4523-8e7c-7c4d31fa9fce

**Comment by justincampbell** [comment]
Hi @junli-lyft! It's normal for the fine-tuning step to take a few days. We'll think about how to make the UI clearer in this regard. I checked on your training, and it's still progressing.

**Comment by junli-lyft** [comment]
> Hi @junli-lyft! It's normal for the fine-tuning step to take a few days. We'll think about how to make the UI clearer in this regard. I checked on your training, and it's still progressing.

Thank you, Justin! It completed successfully today.
